install: 
  - "nuget restore ClassicAssist.sln"
language: csharp
mono: 
  - latest
dotnet: 3.1.302
os: osx
script: 
  - "msbuild /p:Configuration=Debug ClassicAssist.Avalonia"
solution: ClassicAssist.sln
