name: Build Mac Avalonia

on:
  push:
    branches: [avalonia]
  pull_request:
    branches: [avalonia]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Nuget Restore
        run: msbuild ClassicAssist.Avalonia /p:Configuration=Debug -t:restore
      - name: Build with msbuild
        run: msbuild ClassicAssist.Avalonia /p:Configuration=Debug
      - run: |
          find .
        shell: bash
      - name: Upload Plugin Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ClassicAssistOutput
          path: ./Output
  test:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download Plugin Artifacts
        uses: actions/download-artifact@v2
        with:
          name: ClassicAssistOutput
      - run: |
          export CLASSICUO_URL=$(curl --silent --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' "https://api.github.com/repos/andreakarasho/ClassicUO/releases/latest" | jq -r '.assets[0].browser_download_url')
          echo "ClassicUO Download URL: $CLASSICUO_URL"
          curl -L $CLASSICUO_URL -o ClassicUO.zip
          unzip ClassicUO.zip -d ClassicUO
          rm ClassicUO.zip
          find .
        shell: bash
